/*
 * generated by Xtext 2.12.0
 */
package de.tu.darmstadt.es


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KappaLiteStandaloneSetup extends KappaLiteStandaloneSetupGenerated {

	def static void doSetup() {
		new KappaLiteStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
