/*
 * generated by Xtext 2.12.0
 */
package de.tu.darmstadt.es.generator

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class NeoKappaGenerator extends AbstractNeoKappaGernerator {


}
