/*
 * generated by Xtext 2.12.0
 */
package de.tu.darmstadt.es


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NeoKappaStandaloneSetup extends NeoKappaStandaloneSetupGenerated {

	def static void doSetup() {
		new NeoKappaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
